commandPickerMap:
  devtool:
    devtool:
      commands:
        - name: devtool
      path: '@feflow/feflow-plugin-devtool'
      type: devtool
  native:
    config:
      commands:
        - name: config
      path: config.js
      type: native
    doctor:
      commands:
        - name: doctor
      path: doctor.js
      type: native
    help:
      commands:
        - name: help
      path: help.js
      type: native
    info:
      commands:
        - name: info
      path: info.js
      type: native
    init:
      commands:
        - name: init
      path: init.js
      type: native
    install:
      commands:
        - name: install
      path: install.js
      type: native
    list:
      commands:
        - name: list
      path: list.js
      type: native
    logger:
      commands:
        - name: logger
      path: logger.js
      type: native
    upgrade:
      commands:
        - name: upgrade
      path: upgrade.js
      type: native
  plugin: {}
  universal:
    commands:
      type: universal
version: 1.0.0
