name: Changelog

on:
  push:
    branches:
      - 'feat/lerna_changelog'
    tags-ignore:
      - '**'
  pull_request: null
  workflow_call: null

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i
      - run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          npx lerna-changelog >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          GITHUB_AUTH: ${{secrets.GITHUB_TOKEN}}
      - uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: ${{env.CHANGELOG}}
