name: Changelog

on:
  push:
    branches:
      - 'feat/lerna_changelog'
    tags-ignore:
      - '**'
  pull_request: null
  workflow_call: null

jobs:
  test-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: npm i
      - run: npx lerna-changelog
      - run: changelog=`npx lerna-changelog` && echo "CHANGELOG=$changelog" >> $GITHUB_ENV
      - uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: $CHANGELOG
