name: Publish with Lerna

on:
  push:
    tags:
      - "*"

jobs:
  Publish_Workflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v1.0.0
    - name: Git Identity
      run: |
        git config --global user.name 'feflowbot'
        git config --global user.email 'feflowbot@gmail.com'
        git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Prepare repository
      run: git checkout "${GITHUB_REF:11}"
    - name: Pulling
      run: git pull
    - name: Install dependencies
      run: npm i
    - name: Authenticate with Registry
      run: |
          yarn logout
          echo "Tencent/feflow:registry=http://registry.npmjs.org/" > .npmrc
          echo "registry=http://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
      env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    - name: Lerna bootstrap
      run: npx lerna bootstrap
    - name: Lerna build
      run: npx lerna run build
    - name: Publish with Lerna
      run: npx lerna publish --yes --message 'chore(release)' --cd-version=patch
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
