name: Publish

on:
  release:
    types:
      - created

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取所有 tags，让 lerna publish from-git 正常识别待发的包
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        run: npm i && npm run bootstrap
        env:
          CI: true
      - name: Build
        run: npm run build
      - name: Check dist tag
        # 不能使用 npm script 包裹，会污染 stdout
        run: node ./scripts/check-dist-tag.js >> $GITHUB_ENV
      - name: Publish
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Generate changelog
        run: |
          echo 'CHANGELOG<<EOF' >> $GITHUB_ENV
          npx lerna-changelog >> $GITHUB_ENV
          echo 'EOF' >> $GITHUB_ENV
        env:
          GITHUB_AUTH: ${{secrets.GITHUB_TOKEN}}
      - name: Wework notification
        uses: chf007/action-wechat-work@master
        env:
          WECHAT_WORK_BOT_WEBHOOK: ${{secrets.WECHAT_WORK_BOT_WEBHOOK}}
        with:
          msgtype: markdown
          content: ${{env.CHANGELOG}}
