name: Publish

on:
  release:
    types:
      - created

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          cache: npm
          cache-dependency-path: |
            node_modules
            packages/*/node_modules
      - name: Install dependencies
        run: npm ci && npm run bootstrap
      - name: Build
        run: npm run build
      - name: Publish
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
