name: Publish

on:
  release:
    types:
      - created

jobs:
  test:
    uses: ./.github/workflows/test.yml
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # 获取所有 tags，让 lerna publish from-git 正常识别待发的包
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org
          cache: npm
      - name: Install dependencies
        run: npm i && npm run bootstrap
        env:
          CI: true
      - name: Build
        run: npm run build
      - name: Publish
        run: npm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
